version: '3'

services:
  mongo:
    container_name: ts-oo-mongoose_mongo
    image: mongo
    environment: 
      - "MONGO_INITDB_DATABASE=db"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports: 
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - ts-oo-mongoose

networks:
  ts-oo-mongoose:
    name: ts-oo-mongoose
