version: '3'

services:
  mysql:
    container_name: ts-pf-mysql_mysql
    image: mysql:5
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
    ports: 
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - ts-pf-mysql
  
  sequelize:
    container_name: ts-pf-mysql_sequelize
    build: .
    environment:
      NODE_ENV: "development"
      MYSQL_URI: "mysql://root:root@mysql:3306/db"
    depends_on:
      mysql:
        condition: service_healthy
    command: > 
      bash -c "
        npm add sequelize-cli &&
        npx sequelize-cli db:drop && 
        npx sequelize-cli db:create && 
        npx sequelize-cli db:migrate && 
        npx sequelize-cli db:seed:all
      "
    networks:
      - ts-pf-mysql

networks:
  ts-pf-mysql:
    name: ts-pf-mysql
